import { Application } from '../../models/application';

export const DEMO_APPLICATIONS: Application[] = [
  {
    id: 'app-1',
    title: 'Senior Developer',
    company: 'Overpoly',
    location: 'Bucharest',
    status: 'pending',
    appliedAt: '2026-10-07',
  },
  {
    id: 'app-2',
    title: 'UX/UI Designer',
    company: 'Overpoly',
    location: 'Bucharest',
    status: 'pending',
    appliedAt: '2026-10-06',
  },
  {
    id: 'app-3',
    title: 'Inginer IoT',
    company: 'GreenWave Energy',
    location: 'Timișoara',
    status: 'pending',
    appliedAt: '2026-10-04',
  },
  {
    id: 'app-4',
    title: 'HR Business Partner',
    company: 'MediCore Health',
    location: 'Iași',
    status: 'pending',
    appliedAt: '2026-10-02',
  },
  {
    id: 'app-5',
    title: 'Motion Designer',
    company: 'PixelForge Studio',
    location: 'Cluj-Napoca',
    status: 'pending',
    appliedAt: '2026-09-30',
  },
  {
    id: 'app-6',
    title: 'Product Designer',
    company: 'NovaTech Solutions',
    location: 'București',
    status: 'pending',
    appliedAt: '2026-09-28',
  },
  {
    id: 'app-7',
    title: 'DevOps Engineer',
    company: 'GreenWave Energy',
    location: 'Timișoara',
    status: 'pending',
    appliedAt: '2026-09-25',
  },
  {
    id: 'app-8',
    title: 'Flutter Developer',
    company: 'PixelForge Studio',
    location: 'Cluj-Napoca',
    status: 'pending',
    appliedAt: '2026-09-23',
  },
  {
    id: 'app-9',
    title: 'Senior React Developer',
    company: 'NovaTech Solutions',
    location: 'București',
    status: 'pending',
    appliedAt: '2026-09-21',
  },
  {
    id: 'app-10',
    title: 'QA Automation Intern',
    company: 'NovaTech Solutions',
    location: 'București',
    status: 'shortlisted',
    appliedAt: '2026-09-18',
  },
  {
    id: 'app-11',
    title: 'Customer Support Specialist',
    company: 'MediCore Health',
    location: 'Remote',
    status: 'pending',
    appliedAt: '2026-09-15',
  },
  {
    id: 'app-12',
    title: 'Data Analyst',
    company: 'GreenWave Energy',
    location: 'Timișoara',
    status: 'accepted',
    appliedAt: '2026-09-11',
  },
  {
    id: 'app-13',
    title: 'Full-stack Developer',
    company: 'FinPulse',
    location: 'București',
    status: 'shortlisted',
    appliedAt: '2026-09-08',
  },
  {
    id: 'app-14',
    title: 'UI/UX Designer',
    company: 'PixelForge Studio',
    location: 'Cluj-Napoca',
    status: 'shortlisted',
    appliedAt: '2026-09-04',
  },
  {
    id: 'app-15',
    title: 'Security Engineer',
    company: 'FinPulse',
    location: 'Remote',
    status: 'rejected',
    appliedAt: '2026-08-29',
  },
];
